name: PowerfulPerms
main: com.github.cheesesoftware.PowerfulPerms.PowerfulPerms
version: ${version}
author: gustav9797
softdepend: [Vault]
depend: [MVdWUpdater]
load: startup

commands:
 powerfulperms:
  description: The command for modifying permissions.
  aliases: [pp, pop, pow]
  permission: powerfulperms.admin